spring:
  application:
    name: moon
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${com.moon.datasource.host}:${com.moon.datasource.port}/${com.moon.datasource.database}
    username: ${com.moon.datasource.username}
    password: ${com.moon.datasource.password}

  jpa:
    hibernate:
      ddl-auto: update  # Warning: Please do not use in release mode
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

server:
  port: ${com.moon.server.port}

com:
  moon:
    jwt:
      adminSecretKey: ${com.moon.jwt.adminSecretKey}
      adminTtlHours: ${com.moon.jwt.adminTtlHours}
      adminTokenName: ${com.moon.jwt.adminTokenName}